### ISSUE TITLE
deepspeed training, meet the error "ValueError: optimizer got an empty parameter list"

### ISSUE THREAD

**Issue by sunnnnnnnny** [Coobiw/MiniGPT4Qwen#13]
When i run ddp training code "python -m torch.distributed.run --nproc_per_node=2 --master_port=12233 train_pipeline.py --cfg-path lavis/projects/pp_qwen14b/train_pp.yaml --num-stages 2",GPU0 Trainable Params: 3937280， GPU1 Trainable Params: 0.
Because one card is enough to measure parameters, this problem seems to occur. Is this what you mean?
GPU1 Trainable Params: 0
Traceback (most recent call last):
  File "train_pipeline.py", line 260, in <module>
    main()
  File "train_pipeline.py", line 181, in main
    engine, optimizer, _, _ = deepspeed.initialize(
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/__init__.py", line 192, in initialize
    engine = PipelineEngine(args=args,
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 68, in __init__
    super().__init__(*super_args, **super_kwargs)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 307, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1230, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1307, in _configure_basic_optimizer
    optimizer = FusedAdam(
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/ops/adam/fused_adam.py", line 90, in __init__
    super(FusedAdam, self).__init__(params, defaults)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/torch/optim/optimizer.py", line 187, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list
GPU0 Trainable Params: 3937280

**Comment by Coobiw** [comment]
hello，if convenient，I need more of your logs like the layers and their corresponding partition.

---- Replied Message ----
From sunnnnnnnny ***@***.***> Date 03/13/2024 15:25 To Coobiw/MiniGPT4Qwen ***@***.***> Cc Subscribed ***@***.***> Subject [Coobiw/MiniGPT4Qwen] deepspeed training, meet the error "ValueError: optimizer got an empty parameter list" (Issue #13)  

When i run ddp training code "python -m torch.distributed.run --nproc_per_node=2 --master_port=12233 train_pipeline.py --cfg-path lavis/projects/pp_qwen14b/train_pp.yaml --num-stages 2",GPU0 Trainable Params: 3937280， GPU1 Trainable Params: 0.
 Because one card is enough to measure parameters, this problem seems to occur. Is this what you mean?
 GPU1 Trainable Params: 0 Traceback (most recent call last): File "train_pipeline.py", line 260, in <module> main() File "train_pipeline.py", line 181, in main engine, optimizer, _, _ = deepspeed.initialize( File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/__init__.py", line 192, in initialize engine = PipelineEngine(args=args, File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 68, in __init__ super().__init__(*super_args, **super_kwargs) File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 307, in __init__ self._configure_optimizer(optimizer, model_parameters) File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1230, in _configure_optimizer basic_optimizer = self._configure_basic_optimizer(model_parameters) File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1307, in _configure_basic_optimizer optimizer = FusedAdam( File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/ops/adam/fused_adam.py", line 90, in __init__ super(FusedAdam, self).__init__(params, defaults) File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/torch/optim/optimizer.py", line 187, in __init__ raise ValueError("optimizer got an empty parameter list") ValueError: optimizer got an empty parameter list GPU0 Trainable Params: 3937280

**Comment by sunnnnnnnny** [comment]
> hello，if convenient，I need more of your logs like the layers and their corresponding partition.
> […](#)
> ---- Replied Message ---- From sunnnnnnnny ***@***.***> Date 03/13/2024 15:25 To Coobiw/MiniGPT4Qwen ***@***.***> Cc Subscribed ***@***.***> Subject [Coobiw/MiniGPT4Qwen] deepspeed training, meet the error "ValueError: optimizer got an empty parameter list" (Issue #13) When i run ddp training code "python -m torch.distributed.run --nproc_per_node=2 --master_port=12233 train_pipeline.py --cfg-path lavis/projects/pp_qwen14b/train_pp.yaml --num-stages 2",GPU0 Trainable Params: 3937280， GPU1 Trainable Params: 0. Because one card is enough to measure parameters, this problem seems to occur. Is this what you mean? GPU1 Trainable Params: 0 Traceback (most recent call last): File "train_pipeline.py", line 260, in <module> main() File "train_pipeline.py", line 181, in main engine, optimizer, _, _ = deepspeed.initialize( File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/__init__.py", line 192, in initialize engine = PipelineEngine(args=args, File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 68, in __init__ super().__init__(*super_args, **super_kwargs) File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 307, in __init__ self._configure_optimizer(optimizer, model_parameters) File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1230, in _configure_optimizer basic_optimizer = self._configure_basic_optimizer(model_parameters) File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1307, in _configure_basic_optimizer optimizer = FusedAdam( File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/ops/adam/fused_adam.py", line 90, in __init__ super(FusedAdam, self).__init__(params, defaults) File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/torch/optim/optimizer.py", line 187, in __init__ raise ValueError("optimizer got an empty parameter list") ValueError: optimizer got an empty parameter list GPU0 Trainable Params: 3937280 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

[2024-03-13 08:37:15,006] [INFO] [module.py:375:_partition_layers] Partitioning pipeline stages with method uniform
stage=0 layers=25
     0: TokenizerPipeLayer
     1: IndentityPipeLayer
     2: IndentityPipeLayer
     3: IndentityPipeLayer
     4: IndentityPipeLayer
     5: QwenBlockPipeLayer
     6: QwenBlockPipeLayer
     7: QwenBlockPipeLayer
     8: QwenBlockPipeLayer
     9: QwenBlockPipeLayer
    10: QwenBlockPipeLayer
    11: QwenBlockPipeLayer
    12: QwenBlockPipeLayer
    13: QwenBlockPipeLayer
    14: QwenBlockPipeLayer
    15: QwenBlockPipeLayer
    16: QwenBlockPipeLayer
    17: QwenBlockPipeLayer
    18: QwenBlockPipeLayer
    19: QwenBlockPipeLayer
    20: QwenBlockPipeLayer
    21: QwenBlockPipeLayer
    22: QwenBlockPipeLayer
    23: QwenBlockPipeLayer
    24: QwenBlockPipeLayer
stage=1 layers=24
    25: QwenBlockPipeLayer
    26: QwenBlockPipeLayer
    27: QwenBlockPipeLayer
    28: QwenBlockPipeLayer
    29: QwenBlockPipeLayer
    30: QwenBlockPipeLayer
    31: QwenBlockPipeLayer
    32: QwenBlockPipeLayer
    33: QwenBlockPipeLayer
    34: QwenBlockPipeLayer
    35: QwenBlockPipeLayer
    36: QwenBlockPipeLayer
    37: QwenBlockPipeLayer
    38: QwenBlockPipeLayer
    39: QwenBlockPipeLayer
    40: QwenBlockPipeLayer
    41: QwenBlockPipeLayer
    42: QwenBlockPipeLayer
    43: QwenBlockPipeLayer
    44: QwenBlockPipeLayer
    45: FLNPipeLayer
    46: LMPipeLayer
    47: LossPipeLayer
    48: IndentityPipeLayerLast
GPU1 Trainable Params: 0
Traceback (most recent call last):
  File "train_pipeline.py", line 260, in <module>
    main()
  File "train_pipeline.py", line 181, in main
    engine, optimizer, _, _ = deepspeed.initialize(
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/__init__.py", line 191, in initialize
    engine = PipelineEngine(args=args,
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 68, in __init__
    super().__init__(*super_args, **super_kwargs)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 307, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1230, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1307, in _configure_basic_optimizer
    optimizer = FusedAdam(
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/ops/adam/fused_adam.py", line 90, in __init__
    super(FusedAdam, self).__init__(params, defaults)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/torch/optim/optimizer.py", line 187, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list
GPU0 Trainable Params: 3937280
[2024-03-13 08:37:18,791] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed info: version=0.14.0, git-hash=unknown, git-branch=unknown
[2024-03-13 08:37:18,866] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False
Using /home/duser/.cache/torch_extensions/py38_cu118 as PyTorch extensions root...
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3186855 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 3186856) of binary: /home/duser/miniconda3/envs/gpt/bin/python
Traceback (most recent call last):
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_pipeline.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-13_08:37:23
  host      : ubuntu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3186856)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by sunnnnnnnny** [comment]
[2024-03-13 08:37:15,006] [INFO] [module.py:375:_partition_layers] Partitioning pipeline stages with method uniform
stage=0 layers=25
     0: TokenizerPipeLayer
     1: IndentityPipeLayer
     2: IndentityPipeLayer
     3: IndentityPipeLayer
     4: IndentityPipeLayer
     5: QwenBlockPipeLayer
     6: QwenBlockPipeLayer
     7: QwenBlockPipeLayer
     8: QwenBlockPipeLayer
     9: QwenBlockPipeLayer
    10: QwenBlockPipeLayer
    11: QwenBlockPipeLayer
    12: QwenBlockPipeLayer
    13: QwenBlockPipeLayer
    14: QwenBlockPipeLayer
    15: QwenBlockPipeLayer
    16: QwenBlockPipeLayer
    17: QwenBlockPipeLayer
    18: QwenBlockPipeLayer
    19: QwenBlockPipeLayer
    20: QwenBlockPipeLayer
    21: QwenBlockPipeLayer
    22: QwenBlockPipeLayer
    23: QwenBlockPipeLayer
    24: QwenBlockPipeLayer
stage=1 layers=24
    25: QwenBlockPipeLayer
    26: QwenBlockPipeLayer
    27: QwenBlockPipeLayer
    28: QwenBlockPipeLayer
    29: QwenBlockPipeLayer
    30: QwenBlockPipeLayer
    31: QwenBlockPipeLayer
    32: QwenBlockPipeLayer
    33: QwenBlockPipeLayer
    34: QwenBlockPipeLayer
    35: QwenBlockPipeLayer
    36: QwenBlockPipeLayer
    37: QwenBlockPipeLayer
    38: QwenBlockPipeLayer
    39: QwenBlockPipeLayer
    40: QwenBlockPipeLayer
    41: QwenBlockPipeLayer
    42: QwenBlockPipeLayer
    43: QwenBlockPipeLayer
    44: QwenBlockPipeLayer
    45: FLNPipeLayer
    46: LMPipeLayer
    47: LossPipeLayer
    48: IndentityPipeLayerLast
GPU1 Trainable Params: 0
Traceback (most recent call last):
  File "train_pipeline.py", line 260, in <module>
    main()
  File "train_pipeline.py", line 181, in main
    engine, optimizer, _, _ = deepspeed.initialize(
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/__init__.py", line 191, in initialize
    engine = PipelineEngine(args=args,
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 68, in __init__
    super().__init__(*super_args, **super_kwargs)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 307, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1230, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1307, in _configure_basic_optimizer
    optimizer = FusedAdam(
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/ops/adam/fused_adam.py", line 90, in __init__
    super(FusedAdam, self).__init__(params, defaults)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/torch/optim/optimizer.py", line 187, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list
GPU0 Trainable Params: 3937280
[2024-03-13 08:37:18,791] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed info: version=0.14.0, git-hash=unknown, git-branch=unknown
[2024-03-13 08:37:18,866] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False
Using /home/duser/.cache/torch_extensions/py38_cu118 as PyTorch extensions root...
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3186855 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 3186856) of binary: /home/duser/miniconda3/envs/gpt/bin/python
Traceback (most recent call last):
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_pipeline.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-13_08:37:23
  host      : ubuntu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3186856)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by sunnnnnnnny** [comment]
`
[2024-03-13 08:37:15,006] [INFO] [module.py:375:_partition_layers] Partitioning pipeline stages with method uniform
stage=0 layers=25
     0: TokenizerPipeLayer
     1: IndentityPipeLayer
     2: IndentityPipeLayer
     3: IndentityPipeLayer
     4: IndentityPipeLayer
     5: QwenBlockPipeLayer
     6: QwenBlockPipeLayer
     7: QwenBlockPipeLayer
     8: QwenBlockPipeLayer
     9: QwenBlockPipeLayer
    10: QwenBlockPipeLayer
    11: QwenBlockPipeLayer
    12: QwenBlockPipeLayer
    13: QwenBlockPipeLayer
    14: QwenBlockPipeLayer
    15: QwenBlockPipeLayer
    16: QwenBlockPipeLayer
    17: QwenBlockPipeLayer
    18: QwenBlockPipeLayer
    19: QwenBlockPipeLayer
    20: QwenBlockPipeLayer
    21: QwenBlockPipeLayer
    22: QwenBlockPipeLayer
    23: QwenBlockPipeLayer
    24: QwenBlockPipeLayer
stage=1 layers=24
    25: QwenBlockPipeLayer
    26: QwenBlockPipeLayer
    27: QwenBlockPipeLayer
    28: QwenBlockPipeLayer
    29: QwenBlockPipeLayer
    30: QwenBlockPipeLayer
    31: QwenBlockPipeLayer
    32: QwenBlockPipeLayer
    33: QwenBlockPipeLayer
    34: QwenBlockPipeLayer
    35: QwenBlockPipeLayer
    36: QwenBlockPipeLayer
    37: QwenBlockPipeLayer
    38: QwenBlockPipeLayer
    39: QwenBlockPipeLayer
    40: QwenBlockPipeLayer
    41: QwenBlockPipeLayer
    42: QwenBlockPipeLayer
    43: QwenBlockPipeLayer
    44: QwenBlockPipeLayer
    45: FLNPipeLayer
    46: LMPipeLayer
    47: LossPipeLayer
    48: IndentityPipeLayerLast
GPU1 Trainable Params: 0
Traceback (most recent call last):
  File "train_pipeline.py", line 260, in <module>
    main()
  File "train_pipeline.py", line 181, in main
    engine, optimizer, _, _ = deepspeed.initialize(
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/__init__.py", line 191, in initialize
    engine = PipelineEngine(args=args,
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 68, in __init__
    super().__init__(*super_args, **super_kwargs)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 307, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1230, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1307, in _configure_basic_optimizer
    optimizer = FusedAdam(
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/ops/adam/fused_adam.py", line 90, in __init__
    super(FusedAdam, self).__init__(params, defaults)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/torch/optim/optimizer.py", line 187, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list
GPU0 Trainable Params: 3937280
[2024-03-13 08:37:18,791] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed info: version=0.14.0, git-hash=unknown, git-branch=unknown
[2024-03-13 08:37:18,866] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False
Using /home/duser/.cache/torch_extensions/py38_cu118 as PyTorch extensions root...
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3186855 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 3186856) of binary: /home/duser/miniconda3/envs/gpt/bin/python
Traceback (most recent call last):
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_pipeline.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-13_08:37:23
  host      : ubuntu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3186856)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
`

**Comment by sunnnnnnnny** [comment]
[2024-03-13 08:37:15,006] [INFO] [module.py:375:_partition_layers] Partitioning pipeline stages with method uniform
stage=0 layers=25
     0: TokenizerPipeLayer
     1: IndentityPipeLayer
     2: IndentityPipeLayer
     3: IndentityPipeLayer
     4: IndentityPipeLayer
     5: QwenBlockPipeLayer
     6: QwenBlockPipeLayer
     7: QwenBlockPipeLayer
     8: QwenBlockPipeLayer
     9: QwenBlockPipeLayer
    10: QwenBlockPipeLayer
    11: QwenBlockPipeLayer
    12: QwenBlockPipeLayer
    13: QwenBlockPipeLayer
    14: QwenBlockPipeLayer
    15: QwenBlockPipeLayer
    16: QwenBlockPipeLayer
    17: QwenBlockPipeLayer
    18: QwenBlockPipeLayer
    19: QwenBlockPipeLayer
    20: QwenBlockPipeLayer
    21: QwenBlockPipeLayer
    22: QwenBlockPipeLayer
    23: QwenBlockPipeLayer
    24: QwenBlockPipeLayer
stage=1 layers=24
    25: QwenBlockPipeLayer
    26: QwenBlockPipeLayer
    27: QwenBlockPipeLayer
    28: QwenBlockPipeLayer
    29: QwenBlockPipeLayer
    30: QwenBlockPipeLayer
    31: QwenBlockPipeLayer
    32: QwenBlockPipeLayer
    33: QwenBlockPipeLayer
    34: QwenBlockPipeLayer
    35: QwenBlockPipeLayer
    36: QwenBlockPipeLayer
    37: QwenBlockPipeLayer
    38: QwenBlockPipeLayer
    39: QwenBlockPipeLayer
    40: QwenBlockPipeLayer
    41: QwenBlockPipeLayer
    42: QwenBlockPipeLayer
    43: QwenBlockPipeLayer
    44: QwenBlockPipeLayer
    45: FLNPipeLayer
    46: LMPipeLayer
    47: LossPipeLayer
    48: IndentityPipeLayerLast
GPU1 Trainable Params: 0
Traceback (most recent call last):
  File "train_pipeline.py", line 260, in <module>
    main()
  File "train_pipeline.py", line 181, in main
    engine, optimizer, _, _ = deepspeed.initialize(
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/__init__.py", line 191, in initialize
    engine = PipelineEngine(args=args,
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 68, in __init__
    super().__init__(*super_args, **super_kwargs)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 307, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1230, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1307, in _configure_basic_optimizer
    optimizer = FusedAdam(
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/deepspeed/ops/adam/fused_adam.py", line 90, in __init__
    super(FusedAdam, self).__init__(params, defaults)
  File "/home/duser/miniconda3/envs/gpt/lib/python3.8/site-packages/torch/optim/optimizer.py", line 187, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list
GPU0 Trainable Params: 3937280

**Comment by Coobiw** [comment]
I've deleted an `occupy` parameters by mistaskes. I feel sorry for that. The new version has been pushed in [4d370b275810e89bdb28d8210e6e173f3d15ec68](https://github.com/Coobiw/MiniGPT4Qwen/commit/4d370b275810e89bdb28d8210e6e173f3d15ec68). Thanks for your helpful issue!

**Comment by sunnnnnnnny** [comment]
ok,thanks. it works for me.
