### ISSUE TITLE
DeepSpeed CPU-Offload Optimizer CUDAVersionError

### ISSUE THREAD

**Issue by cuczhangyi** [Coobiw/MiniGPT4Qwen#31]
您好，在使用qwen7b sft video 训练过程中，一切OK， 在切换为 qwen14b之后，按照MPPQwen14B_README.md 中进行sft训练的时候，出现了的deepspeed 版本于cuda不匹配的问题，是那里出现了问题么？  

训练命令 python -m torch.distributed.run --nproc_per_node=6 train_pipeline.py --cfg-path lavis/projects/pp_qwen14b/sft_100k_pp.yaml --num-stages 6
 

报错信息：
```
Traceback (most recent call last):
  File "train_pipeline.py", line 261, in <module>
    main()
  File "train_pipeline.py", line 182, in main
    engine, optimizer, _, _ = deepspeed.initialize(
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/__init__.py", line 191, in initialize
    engine = PipelineEngine(args=args,
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 68, in __init__
    super().__init__(*super_args, **super_kwargs)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 307, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1230, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1301, in _configure_basic_optimizer
    optimizer = DeepSpeedCPUAdam(model_parameters,
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 94, in __init__
    self.ds_opt_adam = CPUAdamBuilder().load()
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 479, in load
    return self.jit_load(verbose)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 511, in jit_load
    cxx_args = self.strip_empty_entries(self.cxx_args())
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 766, in cxx_args
    CUDA_ENABLE = self.is_cuda_enable()
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 370, in is_cuda_enable
    assert_no_cuda_mismatch(self.name)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 101, in assert_no_cuda_mismatch
    raise CUDAMismatchException(
deepspeed.ops.op_builder.builder.CUDAMismatchException: >- DeepSpeed Op Builder: Installed CUDA version 12.4 does not match the version torch was compiled with 11.7, unable to compile cuda/cpp extensions without a matching cuda version.
Traceback (most recent call last):
  File "train_pipeline.py", line 261, in <module>
    main()
  File "train_pipeline.py", line 182, in main
    engine, optimizer, _, _ = deepspeed.initialize(
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/__init__.py", line 191, in initialize
    engine = PipelineEngine(args=args,
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 68, in __init__
    super().__init__(*super_args, **super_kwargs)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 307, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1230, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1301, in _configure_basic_optimizer
    optimizer = DeepSpeedCPUAdam(model_parameters,
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 94, in __init__
    self.ds_opt_adam = CPUAdamBuilder().load()
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 479, in load
    return self.jit_load(verbose)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 511, in jit_load
    cxx_args = self.strip_empty_entries(self.cxx_args())
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 766, in cxx_args
    CUDA_ENABLE = self.is_cuda_enable()
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 370, in is_cuda_enable
    assert_no_cuda_mismatch(self.name)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 101, in assert_no_cuda_mismatch
    raise CUDAMismatchException(
deepspeed.ops.op_builder.builder.CUDAMismatchException: >- DeepSpeed Op Builder: Installed CUDA version 12.4 does not match the version torch was compiled with 11.7, unable to compile cuda/cpp extensions without a matching cuda version.
Traceback (most recent call last):
  File "train_pipeline.py", line 261, in <module>
    main()
  File "train_pipeline.py", line 182, in main
    engine, optimizer, _, _ = deepspeed.initialize(
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/__init__.py", line 191, in initialize
Traceback (most recent call last):
  File "train_pipeline.py", line 261, in <module>
    engine = PipelineEngine(args=args,
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 68, in __init__
    super().__init__(*super_args, **super_kwargs)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 307, in __init__
    self._configure_optimizer(optimizer, model_parameters)
      File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1230, in _configure_optimizer
main()
  File "train_pipeline.py", line 182, in main
    engine, optimizer, _, _ = deepspeed.initialize(
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/__init__.py", line 191, in initialize
    engine = PipelineEngine(args=args,
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 68, in __init__
    super().__init__(*super_args, **super_kwargs)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 307, in __init__
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1301, in _configure_basic_optimizer
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1230, in _configure_optimizer
    optimizer = DeepSpeedCPUAdam(model_parameters,
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 94, in __init__
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1301, in _configure_basic_optimizer
    self.ds_opt_adam = CPUAdamBuilder().load()
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 479, in load
    return self.jit_load(verbose)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 511, in jit_load
    optimizer = DeepSpeedCPUAdam(model_parameters,
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 94, in __init__
    cxx_args = self.strip_empty_entries(self.cxx_args())
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 766, in cxx_args
    self.ds_opt_adam = CPUAdamBuilder().load()
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 479, in load
        CUDA_ENABLE = self.is_cuda_enable()return self.jit_load(verbose)

  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 370, in is_cuda_enable
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 511, in jit_load
    assert_no_cuda_mismatch(self.name)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 101, in assert_no_cuda_mismatch
    cxx_args = self.strip_empty_entries(self.cxx_args())
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 766, in cxx_args
    raise CUDAMismatchException(
deepspeed.ops.op_builder.builder.CUDAMismatchException: >- DeepSpeed Op Builder: Installed CUDA version 12.4 does not match the version torch was compiled with 11.7, unable to compile cuda/cpp extensions without a matching cuda version.
    CUDA_ENABLE = self.is_cuda_enable()
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 370, in is_cuda_enable
    assert_no_cuda_mismatch(self.name)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 101, in assert_no_cuda_mismatch
    raise CUDAMismatchException(
deepspeed.ops.op_builder.builder.CUDAMismatchException: >- DeepSpeed Op Builder: Installed CUDA version 12.4 does not match the version torch was compiled with 11.7, unable to compile cuda/cpp extensions without a matching cuda version.
Exception ignored in: <function DeepSpeedCPUAdam.__del__ at 0x7f99247e9dc0>
Traceback (most recent call last):
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 102, in __del__
    self.ds_opt_adam.destroy_adam(self.opt_id)
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'
Exception ignored in: <function DeepSpeedCPUAdam.__del__ at 0x7fe7dc725dc0>
Traceback (most recent call last):
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 102, in __del__
    self.ds_opt_adam.destroy_adam(self.opt_id)
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'
Traceback (most recent call last):
  File "train_pipeline.py", line 261, in <module>
    main()
  File "train_pipeline.py", line 182, in main
    engine, optimizer, _, _ = deepspeed.initialize(
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/__init__.py", line 191, in initialize
    engine = PipelineEngine(args=args,
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 68, in __init__
    super().__init__(*super_args, **super_kwargs)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 307, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1230, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1301, in _configure_basic_optimizer
    optimizer = DeepSpeedCPUAdam(model_parameters,
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 94, in __init__
    self.ds_opt_adam = CPUAdamBuilder().load()
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 479, in load
    return self.jit_load(verbose)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 511, in jit_load
    cxx_args = self.strip_empty_entries(self.cxx_args())
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 766, in cxx_args
    CUDA_ENABLE = self.is_cuda_enable()
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 370, in is_cuda_enable
    assert_no_cuda_mismatch(self.name)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 101, in assert_no_cuda_mismatch
    raise CUDAMismatchException(
deepspeed.ops.op_builder.builder.CUDAMismatchException: >- DeepSpeed Op Builder: Installed CUDA version 12.4 does not match the version torch was compiled with 11.7, unable to compile cuda/cpp extensions without a matching cuda version.
Exception ignored in: <function DeepSpeedCPUAdam.__del__ at 0x7f38b843adc0>
Traceback (most recent call last):
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 102, in __del__
    self.ds_opt_adam.destroy_adam(self.opt_id)
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'
Exception ignored in: <function DeepSpeedCPUAdam.__del__ at 0x7f2f6048cdc0>
Traceback (most recent call last):
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 102, in __del__
    self.ds_opt_adam.destroy_adam(self.opt_id)
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'
Traceback (most recent call last):
  File "train_pipeline.py", line 261, in <module>
    main()
  File "train_pipeline.py", line 182, in main
    engine, optimizer, _, _ = deepspeed.initialize(
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/__init__.py", line 191, in initialize
    engine = PipelineEngine(args=args,
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/runtime/pipe/engine.py", line 68, in __init__
    super().__init__(*super_args, **super_kwargs)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 307, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1230, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1301, in _configure_basic_optimizer
    optimizer = DeepSpeedCPUAdam(model_parameters,
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 94, in __init__
    self.ds_opt_adam = CPUAdamBuilder().load()
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 479, in load
    return self.jit_load(verbose)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 511, in jit_load
    cxx_args = self.strip_empty_entries(self.cxx_args())
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 766, in cxx_args
    CUDA_ENABLE = self.is_cuda_enable()
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 370, in is_cuda_enable
    assert_no_cuda_mismatch(self.name)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 101, in assert_no_cuda_mismatch
    raise CUDAMismatchException(
deepspeed.ops.op_builder.builder.CUDAMismatchException: >- DeepSpeed Op Builder: Installed CUDA version 12.4 does not match the version torch was compiled with 11.7, unable to compile cuda/cpp extensions without a matching cuda version.
Exception ignored in: <function DeepSpeedCPUAdam.__del__ at 0x7f5db4281dc0>
Traceback (most recent call last):
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 102, in __del__
    self.ds_opt_adam.destroy_adam(self.opt_id)
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'
Exception ignored in: <function DeepSpeedCPUAdam.__del__ at 0x7f29c02aedc0>
Traceback (most recent call last):
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 102, in __del__
    self.ds_opt_adam.destroy_adam(self.opt_id)
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1658406) of binary: /home/amax/anaconda3/envs/minigpt4qwen/bin/python
Traceback (most recent call last):
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/amax/anaconda3/envs/minigpt4qwen/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_pipeline.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-07-22_14:27:47
  host      : amax
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1658407)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-07-22_14:27:47
  host      : amax
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1658408)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-07-22_14:27:47
  host      : amax
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1658410)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2024-07-22_14:27:47
  host      : amax
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 1658411)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2024-07-22_14:27:47
  host      : amax
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 1658412)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-22_14:27:47
  host      : amax
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1658406)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
�
```

**Comment by Coobiw** [comment]
你可以试试把使用的config文件里的deepspeed中`offload_optimizer`注释掉即可，DeepSpeed中CPU Offload的optimizer需要torch版本的cuda和当前机器所安装的cuda版本完全匹配

https://github.com/Coobiw/MPP-LLaVA/blob/master/lavis/projects/pp_qwen14b/sft_100k_pp.yaml#L111

**Comment by Coobiw** [comment]
如果修改后没问题的话，麻烦和我说一声～我修改下issue标题并pin一下这个issue方便参考

**Comment by cuczhangyi** [comment]
修改之后就会出现oom ，最后还是换了cuda版本，暂时可以训练了，后续看下效果，谢谢，感恩

**Comment by Coobiw** [comment]
OK, solved. I'll close this issue.
